name: CI

on:
  schedule:
    - cron: "0 */4 * * *" # Runs every 4 hours at minute 0

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run script
        run: |
          echo " " >> README.md
          git config user.name "your_name"
          git config user.email "your_email@email.com"
          git add README.md
          git commit -m "Always green!"
          git push
